### ISSUE TITLE
要怎么用?提示没有cookie

### ISSUE THREAD

**Issue by guyeu9** [hemaolong/youdaopull#4]

**Comment by guyeu9** [comment]
哦哦，得用那几个bat文件先登录，但是现在又发现了新的问题，那就是每次都卡死，一个文件也下不出来，每次运行完准备下载文件的时候就卡死，怎么都没用

**Comment by hemaolong** [comment]
用最新版本的，有道云笔记会经常更新版本，旧的程序无法支持。
