### ISSUE TITLE
一直卡在这里，不会动

### ISSUE THREAD

**Issue by huming971336** [hemaolong/youdaopull#5]
10:54AM INF download file file_size=863268 id=wcp1662085866176414 local_path="ydnote/file/我的资源/收藏笔记/一篇文章彻底弄懂齐次裁剪 - 知乎.note" name="一篇文章彻底弄懂齐次裁剪 - 知乎.note"
10:54AM WRN wait to get file content(changed) get="URP源码学习一整体框架理解知乎1" want="一篇文章彻底弄懂齐次裁剪知乎"
10:54AM INF download file word id=wcp1662085866176414 local_path="F:\\workspace\\youdaopull-master\\youdaopull-master\\bin\\ydnote\\file\\__docx\\我的资源\\收藏笔记\\一篇文章彻底弄懂齐次裁剪知乎note.docx" name="一篇文章彻底弄懂齐次裁剪 - 知乎.note"

一直卡在这里，不会动

**Comment by hemaolong** [comment]
已经解决，请下载最新版本。如果偶尔卡住请点击 "更多" 菜单按钮

**Comment by hemaolong** [comment]
已经修复，请下载最新版本
